### ISSUE TITLE
styles_font_menu not saving

### ISSUE THREAD

**Issue by joepierce** [stylesplugin/styles-font-menu#12] opened 2014-07-02 14:19 UTC
getting much closer to a solution: 

The text fields are saving data now but the "styles_font_menu"  font dropdown still doesn't. 
The issue is apparently in the "function button1text_setting()" function. What would be the best way to write this function?

``` php

function build_options_page() { ?>
<div id="theme-options-wrap">
<form method="post" action="options.php" enctype="multipart/form-data">
<?php settings_fields('theme_options'); ?>
<?php do_settings_sections(__FILE__); ?>
<p>
<input name="Submit" type="submit" value="<?php esc_attr_e('Save Changes'); ?>" />
</p>
</form>
</div>


<?php } add_action('admin_init', 'register_and_build_fields');

function register_and_build_fields() {

register_setting('theme_options', 'theme_options', 'validate_setting');
add_settings_section('homepage_settings', 'Homepage Settings', 'section_homepage', __FILE__);
function section_homepage() {}

add_settings_field('button1text', 'Text Font', 'button1text_setting', __FILE__, 'homepage_settings');
add_settings_field('button1link', 'text field 1', 'button1link_setting', __FILE__, 'homepage_settings');
add_settings_field('button2text', 'text field 2', 'button2text_setting', __FILE__, 'homepage_settings');
}


function validate_setting($theme_options) { return $theme_options; }

function button1text_setting() { 
$options = get_option('theme_options');
$attributes = array(
'name' => 'button1text_setting',
'id' => 'button1text_setting'    );
do_action( 'styles_font_menu', $attributes);
}


function button1link_setting() { $options = get_option('theme_options'); echo "<input name='theme_options[button1link_setting]' type='text' value='{$options['button1link_setting']}' />"; }

function button2text_setting() { $options = get_option('theme_options'); echo "<input name='theme_options[button2text_setting]' type='text' value='{$options['button2text_setting']}' />"; }

add_action('admin_menu', 'theme_options_page');

function theme_options_page() { add_options_page('Theme Settings', 'Theme Settings', 'administrator', __FILE__, 'build_options_page');}

```

 (you can see that the text fields are saving but the font doesn't) This code puts out:

![output](https://cloud.githubusercontent.com/assets/8026754/3459811/be78517a-0210-11e4-9e16-fb49e8867bbc.png)

**Comment by pdclark** [comment] 2014-07-03 21:28
Ah, found it! Closing as a duplicate of #11. Per my notes in that thread, looks like you are setting name, but it should be `theme_options[button1text_setting]`, not `button1text_setting`. Still likely cleaner to use the options framework example in the other thread.

**Comment by joepierce** [comment] 2014-07-03 21:28
so what is the final snip?

**Closed as completed by pdclark** 2014-07-03 21:28 UTC

**Comment by joepierce** [comment] 2014-07-03 21:32
I'm sorry, I'm still not clear on what I should use as a 
best-case-usage-scenario.

please and thank you.
